### ISSUE TITLE
Suggestions not rendered

### ISSUE THREAD

**Issue by tarik** [akdh/cst-tools#1]
Hi,
it's not possible to render the suggestions with the current version of the "render.py" script. Following code contains the necessary fixes. All fixes are commented.

``` python
import pystache, csv, json, sqlite3, sys

if len(sys.argv) != 2:
    print('usage: %s SUGGESTIONS')
    exit()

suggestions_filename = sys.argv[1]

with open('tags.csv') as f:
    reader = csv.reader(f)
    tags = [row[1].decode('utf-8') for row in reader] # Fix: The "pystache" module requires input in Unicode, but the "csv" module returns strings.

with open(suggestions_filename) as f:
    data = json.loads(f.read())

conn = sqlite3.connect('docs.db')
conn.row_factory = sqlite3.Row
cur = conn.cursor()

rows = []
for index in range(len(data['suggestions'])):
    id = data['suggestions'][index]
    cur.execute('select id, title, url, description from docs where id = ?', (id, ))
    row = dict(cur.fetchone())
    row['index'] = index
    rows.append(row) # Fix: Typo.

conn.close()

with open('templates/suggestions.html') as f:
    print (pystache.render(f.read(), {'tags': tags, 'raw_tags': json.dumps(tags), 'documents': rows})).encode('utf-8') # Fix: Necessary if you want to use shell redirection.

```

I'm using Python 2.7.9.

**Comment by aliannejadi** [comment]
Don't you get the error: "no such table: docs" ?

**Comment by tarik** [comment]
Yes, I get this error. The _docs.db_ file is not included, but you can easily create it by importing the data from a CSV file. For this you can use the command line utility [sqlite3](https://www.sqlite.org/cli.html).

**Comment by akdh** [comment]
Specifically you can run

```
sqlite3 docs.db < load_docs.sql
```

`load_docs.sql` can be found here: https://github.com/akdh/cst-tools/blob/master/load_docs.sql

and `collection_2015.csv` (used in) `load_docs.sql` can be found on the track website: https://sites.google.com/site/treccontext/trec-2015.

**Comment by akdh** [comment]
@tarikssalem Thanks! I have (finally) incorporated your suggestions.
